### ISSUE TITLE
Whether authentication is required to initiate a call request

### ISSUE THREAD

**Issue by hewm** [dfinity/response-verification#192]
E.g
`
https://icp-api.io/api/v2/canister/qoctq-giaaa-aaaaa-aaaea-cai/call
`
Such an address will only return a status code. Whether this type of request should also be verified

`
code:  202

content:  b''

request_headers:  [('User-Agent', 'python-requests/2.31.0'), ('Accept-Encoding', 'gzip, deflate'), ('Accept', '*/*'), ('Connection', 'keep-alive'), ('Content-Type', 'application/cbor'), ('Content-Length', '353')]

response_headers:  [('Server', 'nginx/1.21.3'), ('Date', 'Wed, 13 Aug 2023 19:06:53 GMT'), ('Content-Length', '0'), ('Connection', 'keep-alive'), ('X-Request-ID', 'b4657b34-5f54-7aae-8d6d-904f5dd01af6'), ('Access-Control-Allow-Origin', '*'), ('Access-Control-Allow-Methods', 'HEAD, POST'), ('Access-Control-Allow-Headers', 'DNT,User-Agent,X-Requested-With,If-None-Match,If-Modified-Since,Cache-Control,Content-Type,Range,Cookie'), ('Access-Control-Expose-Headers', 'Accept-Ranges,Content-Length,Content-Range'), ('Access-Control-Max-Age', '600'), ('Content-Type', 'application/cbor'), ('X-Content-Type-Options', 'nosniff')]
`

**Comment by nathanosdev** [comment]
Closing since this is not the intended purpose of this library, https://github.com/dfinity/agent-rs is responsible for validating update calls.
