### ISSUE TITLE
Candid v0.10.1

### ISSUE THREAD

**Issue by peterpeterparker** [dfinity/response-verification#251]
I cannot bump Candid in Juno because `ic-certification` still requires v0.9.0.

Therefore openeing this issue. Would be nice if you could upgrade/release one of those day.

**Comment by nathanosdev** [comment]
Thanks David. Support for candid `^0.10` has been released in v2.2.0: https://github.com/dfinity/response-verification/releases/tag/2.2.0.

**Comment by peterpeterparker** [comment]
Super, thanks. I'll bump Juno 😃.
